# Generated by Django 4.1.5 on 2024-05-20 01:11

import administracion.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad_de_medida', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt2s'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/recetas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), administracion.models.validate_image_size])),
                ('nombre', models.CharField(default='Nombre', max_length=150, unique=True)),
                ('descripcion', models.CharField(default='Fabricacion Propia', max_length=150)),
                ('porciones', models.DecimalField(decimal_places=2, default=1, max_digits=15)),
                ('rentabilidad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='ProductoReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('medida_uso', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt2s'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.receta')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'Productos incluidos',
            },
        ),
        migrations.CreateModel(
            name='GastosAdicionalesReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.receta')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'Gastos adicionales',
            },
        ),
    ]
