# Generated by Django 4.1.5 on 2024-05-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoreceta',
            name='cantidad',
            field=models.FloatField(default=1),
        ),
    ]
