# Generated by Django 4.1.5 on 2024-05-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_receta_descripcion_alter_receta_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
