# Generated by Django 4.1.5 on 2024-05-20 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_categoriareceta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.categoriareceta'),
        ),
    ]
