# Generated by Django 4.1.5 on 2024-05-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_receta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriareceta',
            name='usuario',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
