# Generated by Django 4.1.5 on 2024-05-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_categoria_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosadicionalesreceta',
            name='usuario',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productoreceta',
            name='usuario',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='usuario',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
