# Generated by Django 4.1.5 on 2024-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_gastosadicionalesreceta_usuario_producto_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='hacer_publico',
            field=models.BooleanField(default=False),
        ),
    ]
