# Generated by Django 4.1.5 on 2024-05-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_receta_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoreceta',
            options={'verbose_name': 'producto incluido', 'verbose_name_plural': 'Productos incluidos'},
        ),
    ]
