# Generated by Django 4.1.5 on 2024-05-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_alter_productoreceta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
