# Generated by Django 4.1.5 on 2024-05-25 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_alter_receta_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasosReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('detalle', models.TextField()),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.receta')),
            ],
            options={
                'verbose_name': 'pasos',
                'verbose_name_plural': 'Pasos',
            },
        ),
    ]
