# Generated by Django 4.1.5 on 2024-05-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_emprendimiento', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('redes_sociales', models.CharField(blank=True, max_length=200, null=True)),
                ('moneda', models.CharField(default='$', max_length=200)),
            ],
        ),
    ]
