# Generated by Django 4.1.5 on 2024-05-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
