# Generated by Django 4.1.5 on 2024-05-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_configuracion_licencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='mostrar_foto',
            field=models.BooleanField(default=True),
        ),
    ]
