# Generated by Django 4.1.5 on 2024-05-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_dashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
