# Generated by Django 4.1.5 on 2024-05-22 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0011_receta_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_fabricacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LotesProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=1)),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrica.lotes')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.receta')),
            ],
        ),
    ]
