# Generated by Django 4.1.5 on 2024-05-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotes',
            options={'verbose_name': 'lote', 'verbose_name_plural': 'Fabricaciones'},
        ),
    ]
